apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: devops-trg
spec:
  containers:
    - name: app
      image: nginx:latest
      env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: demo-config
              key: database_host