apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-vol
  namespace: devops-trg
spec:
  containers:
    - name: app
      image: nginx:latest
      volumeMounts:
        - name: config
          mountPath: "/etc/app-config"
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: demo-config