apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
    - name: pvc-pod-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /apps
          name: apps  
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: demo-pvc
    - name: apps
      persistentVolumeClaim:
        claimName: pvc-dynamic    